### PR TITLE
Fixed some Italian descriptions

### PR DESCRIPTION
**Pull request by patricknicolosi**

### CODE REVIEW

**Comment by abineshPalanisamy** [comment]
Hi @patricknicolosi ,
 
We have reviewed the DataGrid localization changes on our end. Both the old and new changes address the same translation. We have verified this with Google Translate and have attached a screenshot for your reference.
 
If there are any misunderstandings regarding your requirements, or if your needs differ in any way, please provide us with specific and clear details. This additional information will help us thoroughly address your request and provide an appropriate solution.

- **Images :** [Translate image.zip](https://github.com/user-attachments/files/17040026/Translate.image.zip)

 
Regards,
Abinesh P

**Comment by patricknicolosi** [comment]
> Hi @patricknicolosi ,
> 
> We have reviewed the DataGrid localization changes on our end. Both the old and new changes address the same translation. We have verified this with Google Translate and have attached a screenshot for your reference.
> 
> If there are any misunderstandings regarding your requirements, or if your needs differ in any way, please provide us with specific and clear details. This additional information will help us thoroughly address your request and provide an appropriate solution.
> 
> * **Images :** [Translate image.zip](https://github.com/user-attachments/files/17040026/Translate.image.zip)
> 
> Regards, Abinesh P

"Pulisci filtro" = "clean filter" with "clean" verb
"Filtro pulito" = "clean filter" with "clean" adjective

**Comment by abineshPalanisamy** [comment]
Hi @patricknicolosi ,
 
If you want to add a custom culture beyond the supported languages, you can extend the [SfLocalizations](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fpub.dev%2Fdocumentation%2Fsyncfusion_flutter_core%2Flatest%2Flocalizations%2FSfLocalizations-class.html&data=05%7C02%7Cabinesh.palanisamy%40syncfusion.com%7C71b05b2e80824a7f808808dcd93de0c8%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C638624106997402530%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=p9OMH01HlPdC4n%2FxTD9J%2Ff9uXYJIRK1vR1S5UFZKxOQ%3D&reserved=0) class and override the necessary properties. This approach allows you to customize your language settings. We have provided a sample for your reference; please review it for further details. For more information, refer to the User Guide.

UG link  - [Custom culture support](https://help.syncfusion.com/flutter/globalization#custom-culture-support)

- **Sample :** [SfDataGrid.zip](https://github.com/user-attachments/files/17070903/SfDataGrid.zip)

 
Regards,
Abinesh P

**Comment by VijayakumarMariappan** [comment]
Hi @patricknicolosi 

We suggest you follow the below user guide documentation to modify the respected properties localized strings based on the culture.
UG link: https://help.syncfusion.com/flutter/globalization#custom-culture-support

**Pull request closed without merging**
