### PR TITLE
fix: wrong vietnamese translate

### PR DESCRIPTION
**Pull request by Trung15010802**
This PR addresses multiple localization errors found within the package locale. Several labels and terms were inaccurately translated, leading to confusion or incorrect interpretations by users.

### CODE REVIEW

**Comment by Trung15010802** [comment]
@abineshPalanisamy Could you review it for me please?

**Comment by Trung15010802** [comment]
I see a PR still open from 2021. Can we contribute by open PR ?

**Review by Ngochiendev — COMMENTED** [review]
oke, please merge

**Review by nvbien2000 — COMMENTED** [review]
LGTM

**Comment by VijayakumarMariappan** [comment]
Hi @Trung15010802 

We suggest you follow the below user guide documentation to modify the respected properties localized strings based on the culture.
UG link: https://help.syncfusion.com/flutter/globalization#custom-culture-support

**Pull request closed without merging**
