### PR TITLE
New Feature for filtering Custom Cell Widgets

### PR DESCRIPTION
**Pull request by berslen**
New feature

Problem: When you displaying a widget instead of text, number or date, it was not possible to filter custom widget.

Solution: I've added the new data type and implemented  and updated the necessary methods to make it happen. If a cell wrapped with FilterableWidgetCell, it is asked for the String value, that will be displayed in the filters. This string can be handled however user wants. For the example Id: Name was provided.

If you are planing to implement similar or better solution for this problem I would be happy use that solution as well.

### CODE REVIEW

**Comment by abineshPalanisamy** [comment]
Hi @berslen ,
 
In SfDataGrid, the **FilterBehavior.StrongDataType** is applied by default to the num, string, and DateTime types. Additionally, it can also be applied to user-defined types. To enable this, extend the user-defined type with the Comparable class. 
 
For detailed steps, refer to the user guide link provided for perform filtering to the user-defined type.
 
UG link - [Perform filtering](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fhelp.syncfusion.com%2Fflutter%2Fdatagrid%2Ffiltering%23perform-filtering-to-the-user-defined-type&data=05%7C02%7Cabinesh.palanisamy%40syncfusion.com%7Cb3ca1c9a7097493e6cd208dce13a74a7%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C638632888384444866%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=wPfZKryr97TFNFwbxCozV2UJDA1kBH2r55RJ2kA5Iew%3D&reserved=0)
 
Regards,
Abinesh P

**Comment by berslen** [comment]
> Hi @berslen ,
> 
> In SfDataGrid, the **FilterBehavior.StrongDataType** is applied by default to the num, string, and DateTime types. Additionally, it can also be applied to user-defined types. To enable this, extend the user-defined type with the Comparable class.
> 
> For detailed steps, refer to the user guide link provided for perform filtering to the user-defined type.
> 
> UG link - [Perform filtering](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fhelp.syncfusion.com%2Fflutter%2Fdatagrid%2Ffiltering%23perform-filtering-to-the-user-defined-type&data=05%7C02%7Cabinesh.palanisamy%40syncfusion.com%7Cb3ca1c9a7097493e6cd208dce13a74a7%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C638632888384444866%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=wPfZKryr97TFNFwbxCozV2UJDA1kBH2r55RJ2kA5Iew%3D&reserved=0)
> 
> Regards, Abinesh P

Example code doesnt do what I am trying to do. You can not see the data in the filters.

**Comment by abineshPalanisamy** [comment]
Hi @berslen ,

After a thorough analysis of the code changes made in the pull request, you can achieve your requirements at the sample level itself. In the **FilterableWidgetCell** class, you need to override the [toString](https://api.dart.dev/stable/3.5.3/dart-core/Object/toString.html) method to convert the value to a string. This way, you can retrieve the respective value in the filter popup menu. Additionally, you can structure your **build method** to include both the icon and the text together in the cells.
 
We’ve included a sample for your reference. Please review it for further details.

- **Sample :** [SfDataGrid.zip](https://github.com/user-attachments/files/17241849/SfDataGrid.zip)


As of now, DataGrid does not have support for customizing the appearance of the filter pop-up menu. We have already considered your request as a feature. We will implement this feature in any of our upcoming releases. At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. We appreciate your patience and understanding until then. You can follow up with the below feedback for further details,
 
Feedback link: [51938](https://www.syncfusion.com/feedback/51938/support-for-customizing-the-appearance-of-the-filter-pop-up-menu)
 
Regards,
Abinesh P

**Comment by berslen** [comment]
``> Hi @berslen ,
> 
> After a thorough analysis of the code changes made in the pull request, you can achieve your requirements at the sample level itself. In the **FilterableWidgetCell** class, you need to override the [toString](https://api.dart.dev/stable/3.5.3/dart-core/Object/toString.html) method to convert the value to a string. This way, you can retrieve the respective value in the filter popup menu. Additionally, you can structure your **build method** to include both the icon and the text together in the cells.
> 
> We’ve included a sample for your reference. Please review it for further details.
> 
> * **Sample :** [SfDataGrid.zip](https://github.com/user-attachments/files/17241849/SfDataGrid.zip)
> 
> As of now, DataGrid does not have support for customizing the appearance of the filter pop-up menu. We have already considered your request as a feature. We will implement this feature in any of our upcoming releases. At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. We appreciate your patience and understanding until then. You can follow up with the below feedback for further details,
> 
> Feedback link: [51938](https://www.syncfusion.com/feedback/51938/support-for-customizing-the-appearance-of-the-filter-pop-up-menu)
> 
> Regards, Abinesh P

It's working fine except the when the value is null since toString needs a string to return, it doesn't show up in the filter as '(Blanks)' . Other than that I also needed to add the following to my filterable widget so that there wont be duplicate items in the filter.  But it's not the best practice to add such methods to a StatelessWidget
```
 @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;

    return other is FilterableWidgetCell && other.value == value;
  }

  @override
  int get hashCode => value.hashCode;
```

Beacuse following code to generate the filter elements 
`
 filterElements.addAll(cellValues
          .toSet()
          .map<FilterElement>(
              (Object e) => FilterElement(value: e, isSelected: isSelected(e)))
          .toList());
`

and toSet requires 

`
  /// Creates a [Set] from [elements].
  ///
  /// The created [Set] is a [LinkedHashSet]. As such, it considers elements that
  /// are equal (using [operator ==]) to be indistinguishable, and requires them to
  /// have a compatible [Object.hashCode] implementation.
`

**Comment by abineshPalanisamy** [comment]
Hi @berslen ,
 
Based on the details provided for the (Blanks) issue, please add logic in the sample that returns the string '**Blanks**' instead of an empty value when the value is null. This approach will allow you to display 'Blanks' in the filter popup menu. As you mentioned in your response, we cannot remove duplicate values by overriding the **operator** and **hashCode** in a StatelessWidget due to restrictions from the framework.
 
Additionally, note that holding the **DataGridCell** as a widget can cause performance issues. Instead of using a widget, consider utilizing a custom type class. This approach will also help eliminate duplicate items. By using a custom data class instead of widgets for data representation, we can reduce widget rebuilds and improve performance.
 
We’ve included a code snippets for your reference. Please review it for further details.

```dart
class EmployeeDataSource extends DataGridSource {
 /// Creates the employee data source class with required details.
  EmployeeDataSource({required List<Employee> employeeData}) {
    _employeeData = employeeData
        .map<DataGridRow>((e) => DataGridRow(cells: [
              DataGridCell<int>(columnName: 'id', value: e.id),
              DataGridCell<FilterableWidgetCell>(
                columnName: 'name_designation',
                value: FilterableWidgetCell(
                  value: (e.name.isEmpty && e.designation.isEmpty)
                      ? null
                      : '${e.name} : ${e.designation}',
                  icon: Icons.person,
                  child: Padding(
                    padding: const EdgeInsets.all(8.0),
                    child: Text((e.name.isEmpty && e.designation.isEmpty)
                       ? ''
                       : '${e.name} : ${e.designation}'),
                  ),
                ),
              ),
              DataGridCell<int>(columnName: 'salary', value: e.salary),
            ]))
        .toList();
 }
}

class FilterableWidgetCell extends StatelessWidget
   implements Comparable<FilterableWidgetCell> {
 const FilterableWidgetCell({
   super.key,
   required this.value,
   required this.child,
   required this.icon,
 });
 
 final String? value;
 final Widget child;
 final IconData icon;
 
 @override
 Widget build(BuildContext context) {
   return Container(
     color: Colors.red,
     child: Row(
        children: [
          Icon(icon, size: 20), // Display the icon.
          const SizedBox(width: 8),
          child, // Return the child widget (which can include text).
       ],
     ),
   );
 }
 
 @override
 int compareTo(FilterableWidgetCell other) {
   return (value ?? '').compareTo(other.value ?? '');
 }
 
 @override
 String toString({DiagnosticLevel minLevel = DiagnosticLevel.info}) {
   // Return the value as the string representation.
   return value ?? '(Blanks)';
 }
}
```

Regards,
Abinesh P

**Comment by berslen** [comment]
putting (Blanks) is not the best solution. First reason is it's not localizable. Secondly when exporting datagrid to excel file, it puts (Blanks) for the cells that should be empty string

**Comment by abineshPalanisamy** [comment]
Hi @berslen ,

## First reason is it's not localizable : ##

- As of now, DataGrid does not have support for localizing the filtering pop-up when the cell value is null(Blank). We will implement this feature in any of our upcoming releases. At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. We appreciate your patience and understanding until then. You can follow up with the below feedback for further details,
 
Feedback link: [60252](https://www.syncfusion.com/feedback/60252/support-for-localizing-the-filtering-pop-up-when-the-cell-value-is-nullblank).

## Secondly when exporting datagrid to excel file, it puts (Blanks) for the cells that should be empty string ##

- In SfDataGrid, the cell value can be customized during PDF export by directly setting the cell value of a **PdfGrid** cell through the **PdfCell** property available in the **cellExport callback** argument. Similarly, the cell value can be customized during Excel export by setting the value of the cell via the **excelRange.value** property, which is also available in the cellExport callback argument. For more information, refer to the User Guide.

UG - [pdf](https://help.syncfusion.com/flutter/datagrid/export-to-pdf#customize-cell-values-while-exporting) & [excel](https://help.syncfusion.com/flutter/datagrid/export-to-excel#customize-cell-values-while-exporting)
 
We’ve included a code snippet for your reference. Please review it for further details.

```dart
Future<void> exportDataGridToPdf() async {
    final PdfDocument document = _key.currentState!.exportToPdfDocument(
        fitAllColumnsInOnePage: true,
        cellExport: (details) {
          if (details.cellValue is FilterableWidgetCell) {
            final cellWidget = details.cellValue as FilterableWidgetCell;
            // If the value is null or contains '(Blanks)', export as an empty string
            if (cellWidget.value == null || cellWidget.value == '(Blanks)') {
              details.pdfCell.value = ''; // Export as an empty string
            }
          }
        });
 
    final Future<List<int>> bytesFuture = document.save();
    final List<int> bytes = await bytesFuture;
    await helper.saveAndLaunchFile(bytes, 'DataGrid.pdf');
    document.dispose();
  }
```
Regards,
Abinesh P

**Comment by ashok-kuvaraja** [comment]
Hi @berslen,
 
We are closing this issue now. You can follow the feedback link for further updates. If you need any further assistance, please reopen this. We are always happy to help.

Regards,
Ashok K

**Pull request closed without merging**
