### PR TITLE
✨ Improve Date Formatting and Localization in Syncfusion DataGrid

### PR DESCRIPTION
**Pull request by LincolnJota**
**Improve Date Formatting and Localization in Syncfusion DataGrid:**
Add date formatting support in DataGrid (AdvancedFilter) and localization improvements

**Description:**
This PR adds functionalities for date formatting in `syncfusion_flutter_datagrid` and improves localization support in `syncfusion_localizations` and `syncfusion_flutter_core`.

**Changes Included:**

**syncfusion_flutter_datagrid:**
- **column.dart:**
  - **Line 1964:** Added `_dataGridStateDetails` for dependency injection.
  - **Line 2115:** Refactored `getDisplayValue` to display date based on the mask.
  - **Line 2141:** Created the static method `formatDate` to format a date to `String` based on `DateTime` and mask.
  - **Line 2750:** Added `_dataGridStateDetails` member to the `DataGridCheckboxFilterHelper` class.
  
- **cell_widget.dart:**
  - **Line 1828:** Added mask field `dataGridConfiguration.localization.dateFormat` into `getDisplayValue`.
  - **Line 2059:** Added mask field `dataGridConfiguration.localization.dateFormat` into `getDisplayValue`.

**syncfusion_localizations:**
- **generated_syncfusion_localizations.dart:**
  - Added `dateFormat` getter to all langs in this file.

**syncfusion_flutter_core:**
- **global_localizations.dart:**
  - **Line 13:** Added `dateFormat` field to the abstract class `SfLocalizations`.
  - **Line 492:** Added `dateFormat` to `_DefaultLocalizations`.

**Motivation:**
These changes were implemented to allow better date formatting in `DataGrid` based on user localization preferences. Adding `dateFormat` to localizations ensures that date formatting is consistent with the user's regional settings.

**Checklist:**
- [x] Code follows the contribution guidelines.
- [x] Documentation has been updated as necessary.
- [x] Tests have been added/updated.
- [x] Code has been tested locally.

**Usage Examples:**
**PT_BR:**
Portuguese Example
**EN_US:**
English Example

### CODE REVIEW

**Comment by AdlanDaniel** [comment]
Ficou muito bom esse ajuste!

**Comment by andersonsantos6** [comment]
Gostei. é o que precisamos!

**Comment by abineshPalanisamy** [comment]
Hi @LincolnJota ,
 
Your request has been acknowledged, and we've already logged it as a feature. It will be considered for implementation in one of our upcoming releases. During the planning phase of each release cycle, we evaluate all pending features and select those for implementation based on several criteria, including product vision, technological feasibility, and customer demand. We appreciate your patience and understanding during this process. For further details, please refer to the feedback below.
 
Feedback link: [48883](https://www.syncfusion.com/feedback/48883/support-for-customizing-the-datetime-display-format-in-the-checkbox-filter-within)
 
Regards,
Abinesh P

**Comment by ashok-kuvaraja** [comment]
Hi @LincolnJota,

You can follow up regarding this feature through the provided feedback link. We're closing this issue now.  If you need any further assistance, reopen this issue. We are always happy to help you.

Regards,
Ashok K

**Pull request closed without merging**
